package tfg;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Position.java
//  @ Date : 19/12/2014
//  @ Author : 
//
//




public class Position {
	private double latitude;
	private double longitude;
	private int radius;
	
	public Position(double latitude_, double longitude_ , int radius_) {
		latitude = latitude_;
		longitude = longitude_;
		radius = radius_;
	}
	
	public double getLatitude() {
		return latitude;
	}
	
	public double getLongitude() {
		return longitude;
	}
	
	public int getRadius() {
		return radius;
	}
}
